### ISSUE TITLE
[1.1.2] Dockerizer environnement de l’API

### ISSUE THREAD

**Issue by VicSAU** [OutsideEIP/OutsideServer#3]
- [ ] Jenkins
- [ ] Database (Postgresql)
- [ ] Database client (PGAdmin)

**Comment by luannbertaud** [comment]
PgAdmin: 02460f78311e40ee7a1045e1fe08f6b6a0abd0b4
Database: 49528cab63e2fdb174dd54b05141351ced816516
Server: b06d12a00b2cc0b16c6d99ae2138cc86d5cb43e3
Jenkins gent: e1de3e1d60faf395435ae014d0f6da9eed6f37e5
Jenkins: 9fd6ae6540e4c1277d0c20ef1aacbc8ad9adf667
